--- 
buildvariants: 
  - 
    display_name: "Ubuntu 16.04"
    expansions: 
      venv: ~/venv/bin
    name: ubuntu1604
    run_on: 
      - ubuntu1604-test
    tasks: 
      - 
        name: build-docs
tasks: 
  - 
    commands: 
      - 
        command: git.get_project
        params: 
          directory: docs-mongodb
        type: setup
      - 
        command: shell.exec
        params: 
          script: |
              rm -rf ~/venv
              
              virtualenv ~/venv
              ${venv}/pip install -r requirements.txt
          working_dir: docs-mongodb
      - 
        command: shell.exec
        params: 
          script: |

            . ${venv}/activate

            python3 -m pip install -qqq --upgrade pip || true

            (   cd "~"
                rm -rf dev
                mkdir dev
                cd dev

                git clone --depth=1 https://github.com/mongodb/mut.git

                ( cd mut && python3 -m pip install -r requirements.txt . )
            )

            install_helper mut
            install_helper mut-build
            install_helper mut-convert-redirects
            install_helper mut-images
            install_helper mut-index
            install_helper mut-intersphinx
            install_helper mut-lint
            install_helper mut-publish
            install_helper mut-redirects

            if ! echo "${PATH}" | grep -q "~/bin"; then
                local rc_files=()
                if [ -r ~/.bash_profile ]; then
                    rc_files+=(~/.bash_profile)
                elif [ -r ~/.bashrc ]; then
                    rc_files+=(~/.bashrc)
                fi

                if [ -r ~/.zshenv ]; then
                    rc_files+=(~/.zshenv)
                elif [ -r ~/.zshrc ]; then
                    rc_files+=(~/.zshrc)
                fi

                if [ ! -z "${rc_files[0]}" ] && ask 'Add PATH environment variable?'; then
                    for rc in "${rc_files[@]}"; do
                        printf "\nPATH=\$PATH:%s/bin\n" "~" >> "${rc}"
                    done

                    echo 'Open a new terminal to use the changes'
                else
                    echo ''
                    echo "Add \"export PATH=\$PATH:~/bin\" to your PATH environment variable"
                fi
            fi

            echo "Installed:"
            echo "  mut"
            echo "  mut-build"
            echo "  mut-convert-redirects"
            echo "  mut-images"
            echo "  mut-index"
            echo "  mut-intersphinx"
            echo "  mut-lint"
            echo "  mut-publish"
            echo "  mut-redirects"

          working_dir: docs-mongodb
      - 
        command: shell.exec
        params: 
          script: |
              # remember that this script should be silent if it 
              # manipulates keys
              mkdir ~/.config
              touch ~/.config/giza-aws-authentication.conf
              echo "${aws_key}" > ~/.config/giza-aws-authentication.conf
              echo "${aws_secret}" >> ~/.config/giza-aws-authentication.conf
              chmod 600 ~/.config/giza-aws-authentication.conf
              
              # as an alternative, you could pass the aws keys to the
              # makefile directly if it supports that
          shell: bash
          silent: true
      - 
        command: shell.exec
        params: 
          script: |
              export USER=${github_author}
              
              if [ "${is_patch}" != "true" ]; then
                make publish
                make deploy
              else
                make html
                make stage
              fi
          shell: bash
          working_dir: docs-mongodb
    name: build-docs
